version: '3.8'

services:
  app:
    build: .
    container_name: notion-site-app
    restart: always
    environment:
      - REDIS_HOST=notion-site-redis
    ports:
      - "3000:3000"
    networks:
      - caddy
      - internal
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: notion-site-redis
    restart: always
    networks:
      - internal

networks:
  caddy:
    external: true
  internal:
